const KEY='rs_chatrabash_v1';
const months=['জানুয়ারি','ফেব্রুয়ারি','মার্চ','এপ্রিল','মে','জুন','জুলাই','আগস্ট','সেপ্টেম্বর','অক্টোবর','নভেম্বর','ডিসেম্বর'];
const seed=[
['১০১','ইয়াহিয়া',''],['১০১','জিন্নুর',''],['১০২','আরিফ',''],['১০২','হেলাল',''],['১০৩','মেহেদী হাসান',''],['১০৩','মোরসালিন',''],['১০৪','বখতিয়ার',''],['১০৪','আবু বক্কর সিদ্দিক',''],['১০৫','মুরাদ',''],['১০৫','সোহান রানা',''],['১০৬','সিয়াম',''],['১০৬','হাস্নাত',''],['১০৭','লাভলু','1100'],['১০৭','মেহেদি',''],['১০৮','নাাজিম',''],['১০৮','মজিবুল',''],['১০৯','সোহাগ','1100'],['১০৯','রিয়াদ',''],['১১০','রাশেদ',''],['১১১','সাগর',''],['১১১','মজনু',''],['১১২','সুজন',''],['১১২','জিহাদ',''],['১১৩','শাহরিয়ার',''],['১১৩','তাকাব্বির',''],['১১৪','মুন্না',''],['১১৪','মমিন',''],['১১৫','সোহেল',''],['১১৫','সজীব বাবু',''],['১১৬','প্রান্ত',''],['১১৬','লিমন','1160'],['১১৭','আরিফ',''],['১১৭','রিফাত',''],['১১৮','জাহিদ',''],['১১৯','আবু সাইদ',''],['১২০','অর্ণব','1230'],['১২১','রবিউল','1230']];
const deposits={'নাাজিম':'2200','সাগর':'2500','জিহাদ':'1000'};
let db=load();
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x&&x.members)return x}catch(e){}return {mess:{name:'RS Chatrabash',location:'Park Mor, Rangpur',address:'',monitor:'',phone:''},members:seed.map((s,i)=>({id:String(i+1),room:s[0],name:s[1],rent:s[2],deposit:deposits[s[1]]||'',phone:'',address:'',district:'',upazila:'',joining:'',leaving:'',status:'active',payments:{}}))};}
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function money(n){return '৳'+Number(n||0).toLocaleString('en-US');}
function num(v){return Number(String(v||'').replace(/,/g,''))||0;}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
function calc(m,month){let due=0,adv=0;for(let i=0;i<=month;i++){const rent=num(m.rent), paid=num((m.payments[i]||[]).reduce((a,p)=>a+num(p.amount),0));let bal=rent+due-adv-paid;due=Math.max(bal,0);adv=Math.max(-bal,0)}return {due,adv};}
function calcMonth(m,month){const prev=month===0?{due:0,adv:0}:calc(m,month-1);const paid=num((m.payments[month]||[]).reduce((a,p)=>a+num(p.amount),0));let bal=num(m.rent)+prev.due-prev.adv-paid;return {paid,due:Math.max(bal,0),adv:Math.max(-bal,0),prevDue:prev.due,prevAdv:prev.adv};}
function totalPaid(m){return months.reduce((a,_,i)=>a+num((m.payments[i]||[]).reduce((x,p)=>x+num(p.amount),0)),0)}
function current(m){return calc(m,11)}
function activeMembers(){return db.members.filter(m=>m.status!=='former')}
function render(){renderDashboard();renderBorders();renderPayments();renderReports();renderSettings();document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===location.hash.slice(1)||(!location.hash&&b.dataset.view==='dashboard')));}
function go(v){location.hash=v;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(v).classList.add('active');render();window.scrollTo(0,0)}
window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'dashboard'));
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
function renderDashboard(){const a=activeMembers(), due=a.reduce((s,m)=>s+current(m).due,0), adv=a.reduce((s,m)=>s+current(m).adv,0), rent=a.reduce((s,m)=>s+num(m.rent),0), rooms=new Set(a.map(m=>m.room)).size;const mo=new Date().getMonth();const coll=a.reduce((s,m)=>s+calcMonth(m,mo).paid,0);document.getElementById('dashboard').innerHTML=`<div class="section"><div class="row"><div><h2 style="margin:0">${esc(db.mess.name)}</h2><div class="muted">${esc(db.mess.location||'')}</div></div><button class="btn small" onclick="openMess()">সম্পাদনা</button></div></div><div class="grid section"><div class="stat"><b>${a.length}</b><span>সক্রিয় বর্ডার</span></div><div class="stat"><b>${rooms}</b><span>দখলকৃত রুম</span></div><div class="stat"><b>${money(rent)}</b><span>মাসিক মোট ভাড়া</span></div><div class="stat"><b>${money(coll)}</b><span>${months[mo]} সংগ্রহ</span></div><div class="stat"><b class="dangerText">${money(due)}</b><span>বর্তমান মোট বকেয়া</span></div><div class="stat"><b class="successText">${money(adv)}</b><span>বর্তমান মোট অগ্রিম</span></div><div class="stat"><b>${money(a.reduce((s,m)=>s+num(m.deposit),0))}</b><span>জামানত</span></div><div class="stat"><b>${money(a.reduce((s,m)=>s+totalPaid(m),0))}</b><span>মোট পরিশোধ (২০২৬)</span></div></div><div class="section"><h2>দ্রুত কাজ</h2><div class="toolbar"><button class="btn" onclick="openMember()">+ বর্ডার যোগ</button><button class="btn secondary" onclick="go('payments')">পেমেন্ট দিন</button></div></div><div class="section"><h2>বর্তমান বকেয়া</h2>${a.filter(m=>current(m).due>0).sort((x,y)=>current(y).due-current(x).due).slice(0,8).map(memberRow).join('')||'<div class="card empty">কোনো বকেয়া নেই</div>'}</div>`}
function memberRow(m){const c=current(m);return `<div class="card" onclick="openProfile('${m.id}')"><div class="row"><div><div class="name">${esc(m.name)}</div><div class="muted">রুম ${esc(m.room)} · ভাড়া ${money(m.rent)}</div></div><span class="badge ${c.due?'due':c.adv?'advance':'paid'}">${c.due?`বকেয়া ${money(c.due)}`:c.adv?`অগ্রিম ${money(c.adv)}`:'হিসাব সমান'}</span></div></div>`}
function renderBorders(){const a=db.members;document.getElementById('borders').innerHTML=`<div class="section"><div class="row"><h2>সব বর্ডার</h2><button class="btn small" onclick="openMember()">+ যোগ</button></div><input id="borderSearch" class="search" placeholder="নাম, রুম বা মোবাইল দিয়ে খুঁজুন" oninput="filterBorders()"><div id="borderList" class="section">${a.map(memberRow).join('')}</div></div>`}
function filterBorders(){const q=document.getElementById('borderSearch').value.toLowerCase();document.getElementById('borderList').innerHTML=db.members.filter(m=>[m.name,m.room,m.phone].join(' ').toLowerCase().includes(q)).map(memberRow).join('')||'<div class="empty">কিছু পাওয়া যায়নি</div>'}
function renderPayments(){const a=activeMembers(),mo=new Date().getMonth();document.getElementById('payments').innerHTML=`<div class="section"><div class="row"><h2>পেমেন্ট</h2><button class="btn small" onclick="openPayment()">+ পেমেন্ট</button></div><div class="monthbar">${months.map((m,i)=>`<button class="btn small ${i===mo?'':'secondary'}" onclick="showPaymentMonth(${i})">${m}</button>`).join('')}</div><div id="paymentMonth"></div></div>`;showPaymentMonth(mo)}
function showPaymentMonth(mi){const a=activeMembers();document.getElementById('paymentMonth').innerHTML=`<div class="section"><div class="muted">${months[mi]} ২০২৬ · হলুদ ঘরে প্রকৃত পরিশোধ লিখুন</div>${a.map(m=>{const x=calcMonth(m,mi);return `<div class="card"><div class="row"><div onclick="openProfile('${m.id}')"><div class="name">${esc(m.name)}</div><div class="muted">রুম ${esc(m.room)} · ভাড়া ${money(m.rent)}</div></div><div style="text-align:right"><div class="muted">পরিশোধ ${money(x.paid)}</div><span class="badge ${x.due?'due':x.adv?'advance':'paid'}">${x.due?`বকেয়া ${money(x.due)}`:x.adv?`অগ্রিম ${money(x.adv)}`:'হিসাব সমান'}</span></div></div><button class="btn small" style="margin-top:9px" onclick="openPayment('${m.id}',${mi})">পেমেন্ট যোগ/দেখুন</button></div>`}).join('')}</div>`}
function renderReports(){document.getElementById('reports').innerHTML=`<div class="section"><h2>রিপোর্ট</h2><div class="card"><div class="row"><b>বর্তমান বকেয়া</b><span class="badge due">${money(activeMembers().reduce((s,m)=>s+current(m).due,0))}</span></div><div class="section">${activeMembers().filter(m=>current(m).due>0).map(memberRow).join('')||'<div class="empty">কোনো বকেয়া নেই</div>'}</div></div><div class="card"><div class="row"><b>বর্তমান অগ্রিম</b><span class="badge advance">${money(activeMembers().reduce((s,m)=>s+current(m).adv,0))}</span></div><div class="section">${activeMembers().filter(m=>current(m).adv>0).map(memberRow).join('')||'<div class="empty">কোনো অগ্রিম নেই</div>'}</div></div><div class="card"><b>২০২৬ মাসভিত্তিক সারাংশ</b><div class="tablewrap section"><table class="table"><thead><tr><th>মাস</th><th>ভাড়া</th><th>পরিশোধ</th><th>বকেয়া</th><th>অগ্রিম</th></tr></thead><tbody>${months.map((m,i)=>{const rent=activeMembers().reduce((s,x)=>s+num(x.rent),0),paid=activeMembers().reduce((s,x)=>s+calcMonth(x,i).paid,0),d=activeMembers().reduce((s,x)=>s+calcMonth(x,i).due,0),ad=activeMembers().reduce((s,x)=>s+calcMonth(x,i).adv,0);return `<tr><td>${m}</td><td>${money(rent)}</td><td>${money(paid)}</td><td>${money(d)}</td><td>${money(ad)}</td></tr>`}).join('')}</tbody></table></div></div><button class="btn" onclick="exportCSV()">CSV রিপোর্ট এক্সপোর্ট</button></div>`}
function renderSettings(){document.getElementById('settings').innerHTML=`<div class="section"><h2>সেটিংস ও ডাটা</h2><div class="card"><b>মেস তথ্য</b><p class="muted">${esc(db.mess.name)} · ${esc(db.mess.location)}</p><button class="btn small" onclick="openMess()">সম্পাদনা</button></div><div class="card"><b>ব্যাকআপ</b><p class="muted">আপনার ডাটা এই ফোনের ব্রাউজারে সংরক্ষিত থাকে। ফোন বদলানোর আগে ব্যাকআপ নিন।</p><div class="toolbar"><button class="btn" onclick="backup()">ব্যাকআপ ডাউনলোড</button><label class="btn secondary" style="text-align:center">ব্যাকআপ পুনরুদ্ধার<input type="file" accept="application/json" hidden onchange="restore(event)"></label></div></div><div class="card"><b>অ্যাপ ইনস্টল</b><p class="muted">Chrome-এ অ্যাপটি খুলে মেনু থেকে “Add to Home screen” বা “Install app” নির্বাচন করুন।</p></div><div class="card"><button class="btn danger" onclick="resetData()">সব ডাটা মুছুন</button></div><div class="footerNote">RS Chatrabash · ২০২৬</div></div>`}
function openModal(html){document.getElementById('sheet').innerHTML=html;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()}
function openMess(){openModal(`<h2>মেস তথ্য</h2><div class="field"><label>মেসের নাম</label><input id="mf_name" value="${esc(db.mess.name)}"></div><div class="field"><label>লোকেশন</label><input id="mf_location" value="${esc(db.mess.location)}"></div><div class="field"><label>ঠিকানা</label><input id="mf_address" value="${esc(db.mess.address)}"></div><div class="two"><div class="field"><label>মনিটরের নাম</label><input id="mf_monitor" value="${esc(db.mess.monitor)}"></div><div class="field"><label>মোবাইল</label><input id="mf_phone" value="${esc(db.mess.phone)}"></div></div><div class="actions"><button class="btn secondary" onclick="closeModal()">বাতিল</button><button class="btn" onclick="saveMess()">সংরক্ষণ</button></div>`)}
function saveMess(){db.mess={name:mf_name.value,location:mf_location.value,address:mf_address.value,monitor:mf_monitor.value,phone:mf_phone.value};save();closeModal();render()}
function openMember(id){const m=id?db.members.find(x=>x.id===id):{id:'',room:'',name:'',rent:'',deposit:'',phone:'',address:'',district:'',upazila:'',joining:'',status:'active'};openModal(`<h2>${id?'বর্ডার সম্পাদনা':'নতুন বর্ডার'}</h2><div class="two"><div class="field"><label>নাম</label><input id="f_name" value="${esc(m.name)}"></div><div class="field"><label>রুম নম্বর</label><input id="f_room" value="${esc(m.room)}"></div></div><div class="two"><div class="field"><label>মাসিক ভাড়া</label><input id="f_rent" type="number" min="0" value="${esc(m.rent)}"></div><div class="field"><label>জামানত</label><input id="f_dep" type="number" min="0" value="${esc(m.deposit)}"></div></div><div class="two"><div class="field"><label>মোবাইল</label><input id="f_phone" value="${esc(m.phone)}"></div><div class="field"><label>যোগদানের তারিখ</label><input id="f_join" type="date" value="${esc(m.joining)}"></div></div><div class="field"><label>ঠিকানা</label><input id="f_address" value="${esc(m.address)}"></div><div class="two"><div class="field"><label>উপজেলা</label><input id="f_upazila" value="${esc(m.upazila)}"></div><div class="field"><label>জেলা</label><input id="f_district" value="${esc(m.district)}"></div></div><div class="actions"><button class="btn secondary" onclick="closeModal()">বাতিল</button>${id?`<button class="btn danger" onclick="toggleFormer('${id}')">${m.status==='former'?'সক্রিয় করুন':'সদস্য বিদায়'}</button>`:''}<button class="btn" onclick="saveMember('${id}')">সংরক্ষণ</button></div>`)}
function saveMember(id){let m=id?db.members.find(x=>x.id===id):{id:Date.now().toString(),payments:{},status:'active'};Object.assign(m,{name:f_name.value.trim(),room:f_room.value.trim(),rent:f_rent.value,deposit:f_dep.value,phone:f_phone.value.trim(),joining:f_join.value,address:f_address.value.trim(),upazila:f_upazila.value.trim(),district:f_district.value.trim()});if(!id)db.members.push(m);save();closeModal();render()}
function toggleFormer(id){let m=db.members.find(x=>x.id===id);m.status=m.status==='former'?'active':'former';if(m.status==='former')m.leaving=new Date().toISOString().slice(0,10);save();closeModal();render()}
function openProfile(id){const m=db.members.find(x=>x.id===id), c=current(m);const hist=months.map((mo,i)=>{const x=calcMonth(m,i);const ps=m.payments[i]||[];return `<tr><td>${mo}</td><td>${money(m.rent)}</td><td>${money(x.prevDue)}</td><td>${money(x.prevAdv)}</td><td>${money(x.paid)}</td><td class="${x.due?'dangerText':''}">${money(x.due)}</td><td class="${x.adv?'successText':''}">${money(x.adv)}</td><td>${ps.length?ps.map(p=>`${money(p.amount)} (${esc(p.date||'')})`).join('<br>'):'-'}</td></tr>`}).join('');openModal(`<div class="profileHead"><div class="avatar">${esc(m.name.slice(0,1))}</div><div><h2 style="margin:0">${esc(m.name)}</h2><div class="muted">রুম ${esc(m.room)} · ${m.status==='former'?'সাবেক সদস্য':'সক্রিয়'}</div></div></div><div class="grid section"><div class="stat"><b>${money(m.rent)}</b><span>মাসিক ভাড়া</span></div><div class="stat"><b class="dangerText">${money(c.due)}</b><span>বর্তমান বকেয়া</span></div><div class="stat"><b class="successText">${money(c.adv)}</b><span>বর্তমান অগ্রিম</span></div><div class="stat"><b>${money(m.deposit)}</b><span>জামানত</span></div></div><div class="card section"><b>ব্যক্তিগত তথ্য</b><p class="muted">মোবাইল: ${esc(m.phone||'নেই')}<br>ঠিকানা: ${esc(m.address||'নেই')}<br>উপজেলা: ${esc(m.upazila||'')} · জেলা: ${esc(m.district||'')}<br>যোগদান: ${esc(m.joining||'')}</p></div><div class="row section"><h3>পূর্ণ ১২ মাসের পেমেন্ট ইতিহাস</h3><button class="btn small" onclick="openPayment('${m.id}')">+ পেমেন্ট</button></div><div class="tablewrap"><table class="table"><thead><tr><th>মাস</th><th>ভাড়া</th><th>আগের বকেয়া</th><th>আগের অগ্রিম</th><th>পরিশোধ</th><th>বকেয়া</th><th>অগ্রিম</th><th>লেনদেন</th></tr></thead><tbody>${hist}</tbody></table></div><div class="actions"><button class="btn secondary" onclick="openMember('${m.id}')">প্রোফাইল সম্পাদনা</button><button class="btn secondary" onclick="closeModal()">বন্ধ</button></div>`)}
function openPayment(id,month){let m=id?db.members.find(x=>x.id===id):activeMembers()[0];if(!m)return;let mi=month??new Date().getMonth();let list=m.payments[mi]||[];openModal(`<h2>পেমেন্ট · ${esc(m.name)}</h2><div class="muted">রুম ${esc(m.room)} · ${months[mi]} ২০২৬ · মাসিক ভাড়া ${money(m.rent)}</div><div class="monthbar section">${months.map((x,i)=>`<button class="btn small ${i===mi?'':'secondary'}" onclick="openPayment('${m.id}',${i})">${x}</button>`).join('')}</div><div class="card section"><b>${months[mi]} হিসাব</b><p class="muted">আগের বকেয়া: ${money(calcMonth(m,mi).prevDue)} · আগের অগ্রিম: ${money(calcMonth(m,mi).prevAdv)} · বর্তমান বকেয়া: ${money(calcMonth(m,mi).due)} · অগ্রিম: ${money(calcMonth(m,mi).adv)}</p></div><div id="payList">${list.map((p,j)=>`<div class="card"><div class="row"><span>${esc(p.date||'')}</span><b>${money(p.amount)}</b><button class="btn danger small" onclick="deletePayment('${m.id}',${mi},${j})">মুছুন</button></div></div>`).join('')||'<div class="empty">এই মাসে কোনো পেমেন্ট নেই। ফাঁকা থাকলে ০ টাকা ধরা হবে।</div>'}</div><div class="field"><label>তারিখ</label><input id="p_date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>প্রকৃত পরিশোধের পরিমাণ</label><input id="p_amount" type="number" min="0" placeholder="টাকা লিখুন"></div><div class="actions"><button class="btn secondary" onclick="openProfile('${m.id}')">প্রোফাইল</button><button class="btn" onclick="savePayment('${m.id}',${mi})">পেমেন্ট সংরক্ষণ</button></div>`)}
function savePayment(id,mi){const m=db.members.find(x=>x.id===id),amt=num(p_amount.value);if(amt<0)return;if(!amt){alert('পেমেন্টের পরিমাণ দিন। কেউ টাকা না দিলে পেমেন্ট যোগ করার দরকার নেই।');return}m.payments[mi]=m.payments[mi]||[];m.payments[mi].push({date:p_date.value,amount:amt});save();openPayment(id,mi);render()}
function deletePayment(id,mi,j){if(!confirm('এই পেমেন্ট মুছে ফেলবেন?'))return;db.members.find(x=>x.id===id).payments[mi].splice(j,1);save();openPayment(id,mi);render()}
function backup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='RS_Chatrabash_Backup.json';a.click();URL.revokeObjectURL(a.href)}
function restore(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.members||!x.mess)throw Error();db=x;save();render();alert('ব্যাকআপ সফলভাবে পুনরুদ্ধার হয়েছে।')}catch{alert('ভুল ব্যাকআপ ফাইল।')}};r.readAsText(f)}
function resetData(){if(confirm('সব ডাটা মুছে ডিফল্ট সদস্য তালিকায় ফিরবেন?')){localStorage.removeItem(KEY);db=load();render()}}
function exportCSV(){let rows=[['নাম','রুম','মাস','ভাড়া','আগের বকেয়া','আগের অগ্রিম','পরিশোধ','বকেয়া','অগ্রিম']];activeMembers().forEach(m=>months.forEach((mo,i)=>{const x=calcMonth(m,i);rows.push([m.name,m.room,mo,m.rent,x.prevDue,x.prevAdv,x.paid,x.due,x.adv])}));const csv='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='RS_Chatrabash_2026_Report.csv';a.click()}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
go(location.hash.slice(1)||'dashboard');
